# Generated by Django 5.2.12 on 2026-03-21 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("LW", "Left Wing"),
                            ("ST", "Striker"),
                            ("RW", "Right Wing"),
                            ("CAM", "Attacking Midfielder"),
                            ("LCM", "Left Central Midfielder"),
                            ("RCM", "Right Central Midfielder"),
                            ("CDM", "Central Defensive Midfielder"),
                            ("LB", "Left Back"),
                            ("LCB", "Left Center Back"),
                            ("RCB", "Right Center Back"),
                            ("RB", "Right Back"),
                            ("GK", "Goalkeeper"),
                        ],
                        max_length=5,
                    ),
                ),
                ("attack_stat", models.IntegerField()),
                ("defence_stat", models.IntegerField()),
                ("ovr", models.IntegerField(editable=False)),
                ("rarity", models.CharField(editable=False, max_length=20)),
                ("event_name", models.CharField(default="Base", max_length=100)),
                ("club", models.CharField(max_length=100)),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("BASE", "Base Card"),
                            ("ICON", "Icon Card"),
                            ("EVENT", "Event Card"),
                            ("PREMIUM", "Premium Card"),
                        ],
                        default="BASE",
                        max_length=10,
                    ),
                ),
                (
                    "image_base",
                    models.ImageField(
                        blank=True, null=True, upload_to="card_templates/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "discord_id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("points", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("cards_collected", models.IntegerField(default=0)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_booster", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("RARE", "Rare"),
                            ("EPIC", "Epic"),
                            ("LEGENDARY", "Legendary"),
                        ],
                        max_length=10,
                    ),
                ),
                ("bonus", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("reward_type", models.CharField(max_length=20)),
                ("reward_value", models.CharField(max_length=100)),
                ("uses", models.IntegerField(default=0)),
                ("max_uses", models.IntegerField(default=100)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField(unique=True)),
                ("spawn_channel_id", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caught_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="core.discorduser",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cardtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Lineup 1", max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("formation", models.CharField(default="433", max_length=20)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.discorduser",
                    ),
                ),
                (
                    "at1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_at1",
                        to="core.usercard",
                    ),
                ),
                (
                    "at2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_at2",
                        to="core.usercard",
                    ),
                ),
                (
                    "at3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_at3",
                        to="core.usercard",
                    ),
                ),
                (
                    "df1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_df1",
                        to="core.usercard",
                    ),
                ),
                (
                    "df2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_df2",
                        to="core.usercard",
                    ),
                ),
                (
                    "df3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_df3",
                        to="core.usercard",
                    ),
                ),
                (
                    "df4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_df4",
                        to="core.usercard",
                    ),
                ),
                (
                    "df5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_df5",
                        to="core.usercard",
                    ),
                ),
                (
                    "gk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_gk",
                        to="core.usercard",
                    ),
                ),
                (
                    "md1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_md1",
                        to="core.usercard",
                    ),
                ),
                (
                    "md2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_md2",
                        to="core.usercard",
                    ),
                ),
                (
                    "md3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_md3",
                        to="core.usercard",
                    ),
                ),
                (
                    "md4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_md4",
                        to="core.usercard",
                    ),
                ),
                (
                    "md5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot_md5",
                        to="core.usercard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.logo"
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipped_logo",
                        to="core.discorduser",
                    ),
                ),
            ],
        ),
    ]
