# Generated by Django 5.2.12 on 2026-03-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="last_pack_booster",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="last_pack_daily",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="last_pack_event",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="last_pack_premium",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discorduser",
            name="last_pack_weekly",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
