# Generated by Django 5.2.12 on 2026-03-22 07:33

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_discorduser_last_pack_booster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercard",
            name="card_id",
            field=models.CharField(
                default=core.models.generate_short_id,
                editable=False,
                max_length=8,
                unique=True,
            ),
        ),
    ]
