# Generated by Django 5.2.12 on 2026-03-23 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_usercard_card_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lineup",
            name="sub1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_sub1",
                to="core.usercard",
            ),
        ),
        migrations.AddField(
            model_name="lineup",
            name="sub2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_sub2",
                to="core.usercard",
            ),
        ),
        migrations.AddField(
            model_name="lineup",
            name="sub3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slot_sub3",
                to="core.usercard",
            ),
        ),
    ]
