# Generated by Django 5.2.12 on 2026-03-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_lineup_sub1_lineup_sub2_lineup_sub3"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.BigIntegerField()),
                ("user_id", models.BigIntegerField()),
                ("command_name", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="serversettings",
            name="catch_log_channel_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="serversettings",
            name="command_log_channel_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_id", models.BigIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("USER", "User"), ("GUILD", "Guild")], max_length=5
                    ),
                ),
                ("reason", models.TextField(default="No reason provided")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("target_id", "type")},
            },
        ),
    ]
