# Generated by Django 5.2.12 on 2026-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_commandlog_serversettings_catch_log_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discorduser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
