# Generated by Django 5.2.12 on 2026-04-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_favourite_card"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trade",
            old_name="p1",
            new_name="initiator",
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="p2",
            new_name="receiver",
        ),
        migrations.AddField(
            model_name="trade",
            name="channel_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trade",
            name="state_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
