# Generated by Django 6.0 on 2026-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_p1_trade_initiator_rename_p2_trade_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtemplate',
            name='ovr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='position',
            field=models.CharField(choices=[('LW', 'Left Wing'), ('ST', 'Striker'), ('RW', 'Right Wing'), ('CAM', 'Attacking Midfielder'), ('CM', 'Central Midfielder'), ('CDM', 'Central Defensive Midfielder'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('GK', 'Goalkeeper')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='rarity',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
