# Generated by Django 6.0 on 2026-04-23 20:17

from django.db import migrations


def update_card_positions(apps, schema_editor):
    CardTemplate = apps.get_model('core', 'CardTemplate')
    # Update LCM/RCM to CM
    CardTemplate.objects.filter(position__in=['LCM', 'RCM']).update(position='CM')
    # Update LCB/RCB to CB
    CardTemplate.objects.filter(position__in=['LCB', 'RCB']).update(position='CB')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cardtemplate_ovr_alter_cardtemplate_position_and_more'),
    ]

    operations = [
        migrations.RunPython(update_card_positions),
    ]
