# Generated by Django 5.2.12 on 2026-04-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtemplate',
            name='rarity',
            field=models.CharField(blank=True, choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary'), ('Premium', 'Premium')], max_length=20),
        ),
    ]
