# Generated by Django 5.2.12 on 2026-04-25 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cardtemplate_rarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='reward_value',
        ),
        migrations.AddField(
            model_name='promocode',
            name='reward_card',
            field=models.ForeignKey(blank=True, help_text='Select a specific card if reward type is Specific Card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cardtemplate'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='reward_points',
            field=models.IntegerField(default=0, help_text='Amount of points if reward type is POINTS'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='reward_type',
            field=models.CharField(choices=[('POINTS', 'Points'), ('PACK_DAILY', 'Daily Pack (Base)'), ('PACK_WEEKLY', 'Weekly Pack (Icon)'), ('PACK_EVENT', 'Event Pack (Event)'), ('PACK_PREMIUM', 'Premium Pack (Icon/Event)'), ('CARD', 'Specific Card')], max_length=20),
        ),
    ]
