# Generated by Django 5.2.12 on 2026-05-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_promocode_redemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SPAWN', 'Spawning'), ('PACK', 'Packs')], max_length=10)),
                ('mode', models.CharField(choices=[('RARITY', 'By Rarity'), ('OVR', 'By OVR')], max_length=10)),
                ('rarity', models.CharField(blank=True, choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary'), ('Premium', 'Premium')], max_length=20, null=True)),
                ('min_ovr', models.IntegerField(blank=True, null=True)),
                ('max_ovr', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Drop Rate',
                'verbose_name_plural': 'Drop Rates',
            },
        ),
        migrations.CreateModel(
            name='RateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SPAWN', 'Spawning'), ('PACK', 'Packs')], max_length=10, unique=True)),
                ('mode', models.CharField(choices=[('RARITY', 'By Rarity'), ('OVR', 'By OVR')], default='RARITY', max_length=10)),
            ],
        ),
    ]
