# Generated by Django 5.2.12 on 2026-05-09 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_droprate_rateconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpawnRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(blank=True, choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Epic', 'Epic'), ('Legendary', 'Legendary'), ('Premium', 'Premium')], help_text="Used when mode is 'By Rarity'", max_length=20, null=True)),
                ('min_ovr', models.IntegerField(blank=True, help_text="Min OVR (inclusive). Used when mode is 'By OVR Range'", null=True)),
                ('max_ovr', models.IntegerField(blank=True, help_text="Max OVR (inclusive). Used when mode is 'By OVR Range'", null=True)),
                ('weight', models.FloatField(default=1.0, help_text='Relative weight. Higher = more likely to drop.')),
            ],
            options={
                'verbose_name': 'Drop Rate',
                'verbose_name_plural': 'Drop Rates',
                'ordering': ['-weight'],
            },
        ),
        migrations.DeleteModel(
            name='DropRate',
        ),
        migrations.AlterModelOptions(
            name='rateconfig',
            options={'verbose_name': 'Rate Configuration', 'verbose_name_plural': 'Rate Configurations'},
        ),
        migrations.AlterField(
            model_name='rateconfig',
            name='mode',
            field=models.CharField(choices=[('RARITY', 'By Rarity'), ('OVR', 'By OVR Range')], default='RARITY', max_length=10),
        ),
        migrations.AddField(
            model_name='spawnrate',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='core.rateconfig'),
        ),
    ]
