# Generated by Django 5.2.12 on 2026-05-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_spawnrate_delete_droprate_alter_rateconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.BigIntegerField(unique=True)),
                ('label', models.CharField(blank=True, help_text="Optional label (e.g. 'Server Booster', 'Patreon T1')", max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
