# Generated by Django 5.2.12 on 2026-05-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_premium_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateconfig',
            name='category',
            field=models.CharField(choices=[('SPAWN', 'Spawning'), ('PACK', 'Packs'), ('PACK_PREMIUM', 'Premium Pack')], max_length=20, unique=True),
        ),
    ]
