# Generated by Django 5.2.12 on 2026-05-10 21:45

from django.db import migrations


def seed_pack_premium(apps, schema_editor):
    RateConfig = apps.get_model('core', 'RateConfig')
    SpawnRate = apps.get_model('core', 'SpawnRate')

    config, created = RateConfig.objects.get_or_create(
        category='PACK_PREMIUM',
        defaults={'mode': 'OVR'}
    )
    
    if created or config.rates.count() == 0:
        config.mode = 'OVR'
        config.save()
        SpawnRate.objects.create(config=config, min_ovr=80, max_ovr=84, weight=30.0)
        SpawnRate.objects.create(config=config, min_ovr=85, max_ovr=87, weight=50.0)
        SpawnRate.objects.create(config=config, min_ovr=88, max_ovr=91, weight=15.0)
        SpawnRate.objects.create(config=config, min_ovr=92, max_ovr=99, weight=5.0)


def revert_pack_premium(apps, schema_editor):
    RateConfig = apps.get_model('core', 'RateConfig')
    RateConfig.objects.filter(category='PACK_PREMIUM').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_update_rateconfig_category_length'),
    ]

    operations = [
        migrations.RunPython(seed_pack_premium, revert_pack_premium)
    ]
