# Generated by Django 5.2.12 on 2026-05-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_pack_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='at4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_at4', to='core.usercard'),
        ),
    ]
