# Generated by Django 5.2.12 on 2026-05-18 17:51

from django.db import migrations, models


def migrate_rarities(apps, schema_editor):
    CardTemplate = apps.get_model('core', 'CardTemplate')
    SpawnRate = apps.get_model('core', 'SpawnRate')
    
    mapping = {
        'Common': 'Common I',
        'Uncommon': 'Uncommon I',
        'Rare': 'Rare I',
        'Epic': 'Epic I',
        'Legendary': 'Legendary I',
    }
    
    for old_rarity, new_rarity in mapping.items():
        CardTemplate.objects.filter(rarity=old_rarity).update(rarity=new_rarity)
        SpawnRate.objects.filter(rarity=old_rarity).update(rarity=new_rarity)


def reverse_migrate_rarities(apps, schema_editor):
    CardTemplate = apps.get_model('core', 'CardTemplate')
    SpawnRate = apps.get_model('core', 'SpawnRate')
    
    reverse_mapping = {
        'Common I': 'Common',
        'Common II': 'Common',
        'Common III': 'Common',
        'Uncommon I': 'Uncommon',
        'Uncommon II': 'Uncommon',
        'Uncommon III': 'Uncommon',
        'Rare I': 'Rare',
        'Rare II': 'Rare',
        'Rare III': 'Rare',
        'Epic I': 'Epic',
        'Epic II': 'Epic',
        'Epic III': 'Epic',
        'Legendary I': 'Legendary',
        'Legendary II': 'Legendary',
        'Legendary III': 'Legendary',
    }
    
    for new_rarity, old_rarity in reverse_mapping.items():
        CardTemplate.objects.filter(rarity=new_rarity).update(rarity=old_rarity)
        SpawnRate.objects.filter(rarity=new_rarity).update(rarity=old_rarity)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_at4_to_lineup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtemplate',
            name='rarity',
            field=models.CharField(blank=True, choices=[('Common I', 'Common I (Weight: 0.3, 42.9% of Common)'), ('Common II', 'Common II (Weight: 0.25, 35.7% of Common)'), ('Common III', 'Common III (Weight: 0.15, 21.4% of Common)'), ('Uncommon I', 'Uncommon I (Weight: 0.1, 50.0% of Uncommon)'), ('Uncommon II', 'Uncommon II (Weight: 0.06, 30.0% of Uncommon)'), ('Uncommon III', 'Uncommon III (Weight: 0.04, 20.0% of Uncommon)'), ('Rare I', 'Rare I (Weight: 0.04, 50.0% of Rare)'), ('Rare II', 'Rare II (Weight: 0.025, 31.3% of Rare)'), ('Rare III', 'Rare III (Weight: 0.015, 18.8% of Rare)'), ('Epic I', 'Epic I (Weight: 0.007, 46.7% of Epic)'), ('Epic II', 'Epic II (Weight: 0.005, 33.3% of Epic)'), ('Epic III', 'Epic III (Weight: 0.003, 20.0% of Epic)'), ('Legendary I', 'Legendary I (Weight: 0.0025, 50.0% of Legendary)'), ('Legendary II', 'Legendary II (Weight: 0.0020, 40.0% of Legendary)'), ('Legendary III', 'Legendary III (Weight: 0.0005, 10.0% of Legendary)'), ('Premium', 'Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='spawnrate',
            name='rarity',
            field=models.CharField(blank=True, choices=[('Common I', 'Common I (Weight: 0.3, 42.9% of Common)'), ('Common II', 'Common II (Weight: 0.25, 35.7% of Common)'), ('Common III', 'Common III (Weight: 0.15, 21.4% of Common)'), ('Uncommon I', 'Uncommon I (Weight: 0.1, 50.0% of Uncommon)'), ('Uncommon II', 'Uncommon II (Weight: 0.06, 30.0% of Uncommon)'), ('Uncommon III', 'Uncommon III (Weight: 0.04, 20.0% of Uncommon)'), ('Rare I', 'Rare I (Weight: 0.04, 50.0% of Rare)'), ('Rare II', 'Rare II (Weight: 0.025, 31.3% of Rare)'), ('Rare III', 'Rare III (Weight: 0.015, 18.8% of Rare)'), ('Epic I', 'Epic I (Weight: 0.007, 46.7% of Epic)'), ('Epic II', 'Epic II (Weight: 0.005, 33.3% of Epic)'), ('Epic III', 'Epic III (Weight: 0.003, 20.0% of Epic)'), ('Legendary I', 'Legendary I (Weight: 0.0025, 50.0% of Legendary)'), ('Legendary II', 'Legendary II (Weight: 0.0020, 40.0% of Legendary)'), ('Legendary III', 'Legendary III (Weight: 0.0005, 10.0% of Legendary)'), ('Premium', 'Premium')], help_text="Used when mode is 'By Rarity'", max_length=20, null=True),
        ),
        migrations.RunPython(migrate_rarities, reverse_migrate_rarities),
    ]
