# Generated by Django 5.2.12 on 2026-05-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cardtemplate_rarity_alter_spawnrate_rarity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('reward_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbc_rewards', to='core.cardtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SBCRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('min_ovr', models.IntegerField(blank=True, null=True)),
                ('required_rarity', models.CharField(blank=True, choices=[('Common I', 'Common I (Weight: 0.3, 42.9% of Common)'), ('Common II', 'Common II (Weight: 0.25, 35.7% of Common)'), ('Common III', 'Common III (Weight: 0.15, 21.4% of Common)'), ('Uncommon I', 'Uncommon I (Weight: 0.1, 50.0% of Uncommon)'), ('Uncommon II', 'Uncommon II (Weight: 0.06, 30.0% of Uncommon)'), ('Uncommon III', 'Uncommon III (Weight: 0.04, 20.0% of Uncommon)'), ('Rare I', 'Rare I (Weight: 0.04, 50.0% of Rare)'), ('Rare II', 'Rare II (Weight: 0.025, 31.3% of Rare)'), ('Rare III', 'Rare III (Weight: 0.015, 18.8% of Rare)'), ('Epic I', 'Epic I (Weight: 0.007, 46.7% of Epic)'), ('Epic II', 'Epic II (Weight: 0.005, 33.3% of Epic)'), ('Epic III', 'Epic III (Weight: 0.003, 20.0% of Epic)'), ('Legendary I', 'Legendary I (Weight: 0.0025, 50.0% of Legendary)'), ('Legendary II', 'Legendary II (Weight: 0.0020, 40.0% of Legendary)'), ('Legendary III', 'Legendary III (Weight: 0.0005, 10.0% of Legendary)'), ('Premium', 'Premium')], max_length=20, null=True)),
                ('required_club', models.CharField(blank=True, max_length=100, null=True)),
                ('required_position', models.CharField(blank=True, choices=[('LW', 'Left Wing'), ('ST', 'Striker'), ('RW', 'Right Wing'), ('CAM', 'Attacking Midfielder'), ('CM', 'Central Midfielder'), ('CDM', 'Central Defensive Midfielder'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('GK', 'Goalkeeper')], max_length=5, null=True)),
                ('sbc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.sbc')),
                ('specific_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.cardtemplate')),
            ],
        ),
    ]
