# Generated by Django 5.2.12 on 2026-05-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sbc_sbcrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_inventory_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercard',
            name='traded_by',
            field=models.ForeignKey(blank=True, help_text='The user who last traded this card to the current owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_traded_away', to='core.discorduser'),
        ),
    ]
