# Generated by Django 6.0 on 2026-05-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_discorduser_is_inventory_private_usercard_traded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the pack', max_length=100)),
                ('code', models.CharField(help_text="Unique slug for commands (e.g., 'summer', 'daily')", max_length=50, unique=True)),
                ('cooldown_days', models.FloatField(default=1.0)),
                ('is_premium_only', models.BooleanField(default=False)),
                ('card_type_filter', models.CharField(choices=[('ANY', 'Any'), ('BASE', 'Base Card'), ('ICON', 'Icon Card'), ('EVENT', 'Event Card'), ('PREMIUM', 'Premium Card')], default='ANY', max_length=20)),
                ('event_name_filter', models.CharField(blank=True, help_text='Require specific event name', max_length=100, null=True)),
                ('rate_config_category', models.CharField(blank=True, help_text='The category string matching a RateConfig (e.g., PACK, PACK_PREMIUM, or PACK_CUSTOM)', max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rateconfig',
            name='category',
            field=models.CharField(help_text='Category or unique slug for this rate config (e.g. PACK_SUMMER)', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='UserPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stash_count', models.IntegerField(default=0, help_text='Number of packs the user has stashed (bypasses cooldown)')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='core.discorduser')),
            ],
            options={
                'unique_together': {('user', 'pack')},
            },
        ),
    ]
