# Generated by Django 5.2.12 on 2026-06-18 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pack_alter_rateconfig_category_userpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='max_ovr_filter',
            field=models.IntegerField(blank=True, help_text='Maximum OVR for cards in this pack (inclusive)', null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='min_ovr_filter',
            field=models.IntegerField(blank=True, help_text='Minimum OVR for cards in this pack (inclusive)', null=True),
        ),
        migrations.AddField(
            model_name='sbc',
            name='reward_pack',
            field=models.ForeignKey(blank=True, help_text='Reward pack to stash (leave blank if rewarding a card instead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbc_rewards', to='core.pack'),
        ),
        migrations.AddField(
            model_name='sbc',
            name='reward_pack_count',
            field=models.IntegerField(default=1, help_text='Number of packs to stash as reward'),
        ),
        migrations.AlterField(
            model_name='sbc',
            name='reward_card',
            field=models.ForeignKey(blank=True, help_text='Specific card reward (leave blank if rewarding a pack instead)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbc_rewards', to='core.cardtemplate'),
        ),
    ]
