# Generated by Django 5.2.12 on 2026-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_season_discorduser_total_packs_opened_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='donation_policy',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FRIENDS', 'Friends Only'), ('PRIVATE', 'Private')], default='OPEN', max_length=10),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='core.discorduser'),
        ),
    ]
