# Generated by Django 5.2.16 on 2026-08-02 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_discorduser_donation_policy_discorduser_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyObjectiveTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_type', models.CharField(choices=[('open_pack', 'Open Packs'), ('perform_trade', 'Perform Trades'), ('play_match', 'Play Matches'), ('finish_sbc', 'Finish SBC'), ('claim_card', 'Claim Cards'), ('play_wager', 'Play Wagers')], max_length=20)),
                ('target_amount', models.IntegerField(default=1)),
                ('description', models.CharField(help_text='e.g. Play 3 matches', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectiveRewardPoolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reward_type', models.CharField(choices=[('POINTS', 'Points'), ('PACK', 'Pack'), ('CARD', 'Specific Card')], max_length=20)),
                ('amount', models.IntegerField(default=1, help_text='Amount of points or packs')),
                ('weight', models.IntegerField(default=10, help_text='Higher weight = more likely to drop')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cardtemplate')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDailyObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('is_claimed', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dailyobjectivetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_objectives', to='core.discorduser')),
            ],
            options={
                'unique_together': {('user', 'template', 'date')},
            },
        ),
    ]
