# Generated by Django 5.2.16 on 2026-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_dailyobjectivetemplate_objectiverewardpoolitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='tactic',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('attacking', 'Attacking'), ('defensive', 'Defensive'), ('possession', 'Possession'), ('counter', 'Counter Attack')], default='balanced', max_length=20),
        ),
    ]
