# Generated by Django 5.2.16 on 2026-08-12 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_tactic_to_lineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimSeasonPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophies', models.IntegerField(default=1000)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.simseason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_seasons', to='core.discorduser')),
            ],
            options={
                'unique_together': {('season', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TradeObjectiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discorduser')),
            ],
            options={
                'unique_together': {('trade', 'user')},
            },
        ),
    ]
